### Config file for running the SMOTE-MSFB pipeline ###

## High level 
main_section:
  sampling_strategy: 1  ## Balance the no. of minority and majority samples
  neighbours_to_consider_for_neighbourhood: 5  ## No. of meighbourhood samples to construct the synthetic sample

## Section helps in identifying the minority samples to be used for generating synthetic samples. 
get_minority_obs_to_resample:
  filter_anamoly: True
  classification_model: "LogisticRegression(max_iter=1000)"  #"DecisionTreeClassifier(max_depth=2, random_state=42)"
  limit_miss_classification_prob: 0.5     
  limit_miss_classification_prob_revised: 0.75
  prob_threshold: 0.1  ## Noise case 1 <- For identifying the samples which are to be EXCLUDED of synthetic data generation
  fallback_threshold: 0.05
  n_estimators: 4
  cv: 4
  min_fraction: 0.05

## Metrics used for identifying the relevant features for neighbourhood definition
feature_selection:
  Percent_MI: 0.95      ## Proportion of MI contributed by top features
  metric: "mutual_info" ## FI importance criteria used

## Metrics for incorporating hubness into the algorithm
hubness:
  incorporate_hubness: True
  top_features_only: True

## The cut-off to set the individual feature to 1 of the synthetic observation. 0.20 means if 20% of the selected samples and its neighbours have a 1 in that feature it will be set to 1 in the synthetic observation generated. This can handle the sparseness in the data.
synthetic_sample_generation:
  cut_off: 0.20

## Flag to generate a lot of print statements to check if everything is working or not.  
logging:
  diagnostic: True
  #level: "INFO"
  #save_results: true

## code for reproduceability 
random_state: 546398